[package]
name = "scripthookv"
version = "0.1.0"
edition = "2021"

[lib]
name = "scripthookv"
path = "src/lib.rs"

[dependencies]
winapi = { version = "0.3.9",  features = ["std"] }
shv_bindings = { path = "../shv_bindings" }
