[package]
name = "scripthookv-rs-gta"
version = "0.1.0"
edition = "2021"

[lib]
name = "scripthookv_gta"
path = "src/lib.rs"

[dependencies]
scripthookv-rs = { path = "../scripthookv-rs" }
joaat = "0.1.0"
strum = "0.23"
strum_macros = "0.23"
num_enum = "0.5.5"
once_cell = "1.9.0"
