[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
name = "example"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "winnt"] }
scripthookv-rs = { path = "../scripthookv-rs" }