[package]
name = "scripthookv-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "scripthookv"
path = "src/lib.rs"

[dependencies]
winapi = { version = "0.3.9",  features = ["std", "minwindef"] }
libscripthookv-sys = { path = "../libscripthookv-sys" }
